### ISSUE TITLE
ppc64le: Random "killed" during Aligning Unionized Grid

### ISSUE THREAD

**Issue by jlost** [ANL-CESAR/XSBench#4]
Hi, I'm on a ppc64le system using MPI compiled with xlc/xlC/xlf. My Makefile configuration is as follows:

```
COMPILER    = gnu
OPTIMIZE    = yes
DEBUG       = yes
PROFILE     = no
MPI         = yes
PAPI        = no
VEC_INFO    = no
VERIFY      = no
BENCHMARK   = no
BINARY_DUMP = no
BINARY_READ = no
```
(leaving "gnu" as the compiler doesn't seem to matter, since "MPI = yes" causes "cc = mpicc")

It compiles successfully, but when I run, it will sometimes print "killed" during Aligning Unionized Grid at random percentages typically above 50%. 

This seems not to happen when the gcc compiler is used (no MPI).  

Running gdb has not offered much insight. Here is the output of a failure while running gdb:
```
[u0017592@sys-85165 src]$ gdb ./XSBench
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.ael7b
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/u0017592/projects/ase-3.13.0b1/XSBench/src/XSBench...done.
(gdb) run
Starting program: /home/u0017592/projects/ase-3.13.0b1/XSBench/src/./XSBench
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/power8/libthread_db.so.1".
Detaching after fork from child process 24746.
[New Thread 0x3fffb72cf0d0 (LWP 24750)]
[New Thread 0x3fffb696f0d0 (LWP 24751)]
================================================================================
                   __   __ ___________                 _
                   \ \ / //  ___| ___ \               | |
                    \ V / \ `--.| |_/ / ___ _ __   ___| |__
                    /   \  `--. \ ___ \/ _ \ '_ \ / __| '_ \
                   / /^\ \/\__/ / |_/ /  __/ | | | (__| | | |
                   \/   \/\____/\____/ \___|_| |_|\___|_| |_|

================================================================================
                    Developed at Argonne National Laboratory
                                   Version: 13
================================================================================
                                  INPUT SUMMARY
================================================================================
Materials:                    12
H-M Benchmark Size:           large
Total Nuclides:               355
Gridpoints (per Nuclide):     11,303
Unionized Energy Gridpoints:  4,012,565
XS Lookups:                   15,000,000
MPI Ranks:                    1
OMP Threads per MPI Rank:     2
Mem Usage per MPI Rank (MB):  5,678
================================================================================
                                 INITIALIZATION
================================================================================
Generating Nuclide Energy Grids...
Sorting Nuclide Energy Grids...
Generating Unionized Energy Grid...
Copying and Sorting all nuclide grids...
Assigning energies to unionized grid...
Assigning pointers to Unionized Energy Grid...
[New Thread 0x3fffb591f0d0 (LWP 24752)]
Aligning Unionized Grid[Thread 0x3fffb7ff79d0 (LWP 24743) exited]
[Thread 0x3fffb591f0d0 (LWP 24752) exited]
[Thread 0x3fffb696f0d0 (LWP 24751) exited]
[Inferior 1 (process 24743) exited with code 0315]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.ael7b.ppc64le libgcc-4.8.3-9.ael7b.ppc64le libstdc++-4.8.3-9.ael7b.ppc64le
```
The above run offered no backtrace. I ran it again, though, and got slightly different results as well as a backtrace: 

```
...

Assigning pointers to Unionized Energy Grid...
[New Thread 0x3fffb591f0d0 (LWP 24899)]
Alig^Cng Unionized Grid...(12% complete)
Program received signal SIGINT, Interrupt.
binary_search (A=0x0, quarry=11.743114876173937, n=11303) at XSutils.c:53
53              if( A[0].energy > quarry )
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.ael7b.ppc64le libgcc-4.8.3-9.ael7b.ppc64le libstdc++-4.8.3-9.ael7b.ppc64le
(gdb) bt
#0  binary_search (A=0x0, quarry=11.743114876173937, n=11303) at XSutils.c:53
#1  0x000000001000480c in set_grid_ptrs$_$OL$_$1$_$OL$_$2 () at GridInit.c:145
#2  0x0000000010004644 in set_grid_ptrs$_$OL$_$1 () at GridInit.c:134
#3  0x00003fffb7bec52c in _lomp_Parallel_StartDefault () from /opt/ibm/lib/libxlsmp.so.1
#4  0x0000000010004554 in set_grid_ptrs (energy_grid=0x3fffac2c0010, nuclide_grids=0x101377a0, n_isotopes=355, n_gridpoints=11303)
    at GridInit.c:131
#5  0x0000000010001858 in main (argc=1, argv=0x3ffffffff4b8) at Main.c:85

```

One more run:

```
Assigning pointers to Unionized Energy Grid...
[New Thread 0x3fffb591f0d0 (LWP 24928)]
Alignin[Thread 0x3fffb591f0d0 (LWP 24928) exited]
[Thread 0x3fffb696f0d0 (LWP 24927) exited]
[Thread 0x3fffb72cf0d0 (LWP 24926) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
```

**Comment by jlost** [comment]
This also occurs when compiled with gcc and running with a single thread.

**Comment by jtramm** [comment]
I'm not able to reproduce this bug. I've tried to do so compiling with gcc 4.4.7 and running on a Power 7 machine (IBM,8205-E6D), but it seems to run cleanly. It appears based on your report that there is something going wrong with the energy point generation, as I think all quarry numbers should be between 0.0 and 1.0.

One potential workaround at least would be to compile it without MPI, and also compile with the BINARY_DUMP option. This will output the initialized data structures that are being generated in the initialization phase where you are getting your segfault. You can then recompile with MPI and BINARY_READ to use that file, hopefully sidestepping the seg fault.

Also, another idea might be checking sizeof(long) on your system. Hopefully it is 8 bytes, otherwise may need to change all variables to "long long" or "ulong". Another idea might be to check to make sure you have enough RAM and that allocations are not returning null. Each MPI rank needs at least 6GB or so.

Anyway, I'd like to be more helpful, but hard to debug when I cannot reproduce the issue.

Also, just to make sure you are aware, XSBench has MPI but only has it to meet power monitoring requirements for BG/Q wherein power monitoring can only be accomplished at the rack level of 512 nodes. In XSBench, all nodes just do the same thing then report some timing statistics at the end -- the MPI comm pattern is not meant to reflect a real MC application like OpenMC. XSBench just mimics the computational load on a single node and is useful for doing shared memory performance analysis on the single node level.

**Comment by jlost** [comment]
Sounds like it might be a RAM issue -- I'm at 4 GB, which is the max for my VM. My sizeof(long) is 8 bytes. I can also try the BINARY_DUMP/BINARY_READ and see if that happens to solve the problem. If not, I'll just have to wait for a beefier machine. Thanks.

**Comment by jtramm** [comment]
Yeah, must be out of memory. XSBench has an alternative "small" problem mode that uses a lot less memory. This can be run via "./XSBench -s small".
